[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "geojson-formatter"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.8"'
]